"""Closes PROJECT_PLAN.md's Phase 10 acceptance bar: "answer_sheet.pdf
matches generated paper's questions 1:1." Reuses the same realistic
4-question fixture Phase 9's rendering integration test used, validates it,
builds the answer key straight from the questions (spec §20: never
regenerated by an LLM), checks the 1:1 correspondence explicitly, then
renders and checks the output is a well-formed, non-trivial PDF."""

from pathlib import Path

from app.backend.answer_key.builder import build_answer_key
from app.backend.rendering.renderer import render_answer_sheet
from app.backend.validation.validator import validate_paper
from tests.integration.test_render_question_paper import _paper, _questions


def test_answer_key_matches_a_validated_papers_questions_1_to_1_and_renders(tmp_path: Path):
    questions = _questions()
    paper = _paper(total_marks=sum(q.marks for q in questions))
    assert validate_paper(paper, questions) == []

    answer_key = build_answer_key(paper, questions)

    assert len(answer_key.entries) == len(questions)
    for entry, question in zip(answer_key.entries, questions, strict=True):
        assert entry.question_id == question.id
        assert entry.question_number == question.question_number
        assert entry.answer == question.expected_answer
        assert entry.marks == question.marks

    output_path = render_answer_sheet(paper, answer_key, tmp_path / "answer_sheet.pdf")

    content = output_path.read_bytes()
    assert content.startswith(b"%PDF-")
    assert b"%%EOF" in content[-64:]
    assert len(content) > 500
